export const FETCH_ALL_LEAGUES_SUCCESS = 'FETCH_ALL_LEAGUES_SUCCESS';
export const FETCH_LEAGUE_BY_ID_SUCCESS = 'FETCH_LEAGUE_BY_ID_SUCCESS';

export const FETCH_ALL_PLAYERS_SUCCESS = 'FETCH_ALL_PLAYERS_SUCCESS';
