league:
  _id:           'ffc_2017'
  auctionBudget: 200
  roster:
    - 'QB'
    - 'RB'
    - 'RB'
    - 'WR'
    - 'WR'
    - 'TE'
    - 'FLEX'
    - 'K'
    - 'D/ST'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
teams:
  - _id:         'ffc_bmac'
    manager:     'bmac'
    name:        'Brian''s Unreal Team'
  - _id:         'ffc_rich'
    manager:     'rich'
    name:        'Cruz Control'
  - _id:         'ffc_kollar'
    manager:     'kollar'
    name:        'Dez Nutt$ 4 Prez'
  - _id:         'ffc_adam'
    manager:     'adam'
    name:        'Division Champs'
  - _id:         'ffc_yurk'
    manager:     'yurk'
    name:        'Injured Easley'
  - _id:         'ffc_eric'
    manager:     'eric'
    name:        'Jefe'
  - _id:         'ffc_brendan'
    manager:     'brendan'
    name:        'Jim Bob Cooters Men'
  - _id:         'ffc_mark'
    manager:     'mark'
    name:        'Mark'
  - _id:         'ffc_robbie'
    manager:     'robbie'
    name:        'Peanutbutter Gumball'
  - _id:         'ffc_dan'
    manager:     'dan'
    name:        'Show me your TDs'
  - _id:         'ffc_voucas'
    manager:     'voucas'
    name:        'Teddy KGB'
  - _id:         'ffc_rob'
    manager:     'rob'
    name:        'Terrible Towelies'
  - _id:         'ffc_banten'
    manager:     'banten'
    name:        'The Sharknados'
  - _id:         'ffc_nick'
    manager:     'nick'
    name:        'Thuney or Not Thuney'
