league:
  _id:           'ffc_2017'
  auctionBudget: 200
  roster:
    - 'QB'
    - 'RB'
    - 'RB'
    - 'WR'
    - 'WR'
    - 'TE'
    - 'FLEX'
    - 'K'
    - 'D/ST'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
teams:
  - _id:         'bmac'
    name:        'Brian''s Unreal Team'
  - _id:         'rich'
    name:        'Cruz Control'
  - _id:         'kollar'
    name:        'Dez Nutt$ 4 Prez'
  - _id:         'adam'
    name:        'Division Champs'
  - _id:         'yurk'
    name:        'Injured Easley'
  - _id:         'eric'
    name:        'Jefe'
  - _id:         'brendan'
    name:        'Jim Bob Cooters Men'
  - _id:         'mark'
    name:        'Mark'
  - _id:         'robbie'
    name:        'Peanutbutter Gumball'
  - _id:         'dan'
    name:        'Show me your TDs'
  - _id:         'voucas'
    name:        'Teddy KGB'
  - _id:         'rob'
    name:        'Terrible Towelies'
  - _id:         'banten'
    name:        'The Sharknados'
  - _id:         'nick'
    name:        'Thuney or Not Thuney'
