league:
  _id:           'gtp_2017'
  auctionBudget: 200
  roster:
    - 'QB'
    - 'RB'
    - 'RB'
    - 'WR'
    - 'WR'
    - 'TE'
    - 'FLEX'
    - 'K'
    - 'D/ST'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'IR'
teams:
  - _id:         'gtp_vince'
    manager:     'vince'
    name:        'William Penny Jenner'
  - _id:         'gtp_nick'
    manager:     'nick'
    name:        'Malcolm in the Mitchell'
  - _id:         'gtp_patterson'
    manager:     'patterson'
    name:        'Cooley And The Gang'
  - _id:         'gtp_gates'
    manager:     'gates'
    name:        'It''s Miller Time'
  - _id:         'gtp_yale'
    manager:     'yale'
    name:        'Mr. Rodger''s Shady Hood'
  - _id:         'gtp_nyle'
    manager:     'nyle'
    name:        'Finkle is Einhorn'
  - _id:         'gtp_lamont'
    manager:     'lamont'
    name:        'Some guys like old balls'
  - _id:         'gtp_penn'
    manager:     'penn'
    name:        'I''ll show my Ditka'
  - _id:         'gtp_kyle'
    manager:     'kyle'
    name:        'RIP Alex Rodriguez'
  - _id:         'gtp_dev'
    manager:     'dev'
    name:        'Turn Down for Watt'
