league:
  _id:           'gtp_2017'
  auctionBudget: 200
  roster:
    - 'QB'
    - 'RB'
    - 'RB'
    - 'WR'
    - 'WR'
    - 'TE'
    - 'FLEX'
    - 'K'
    - 'D/ST'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'BN'
    - 'IR'
teams:
  - _id:         'vince'
    name:        'William Penny Jenner'
  - _id:         'makes'
    name:        'Malcolm in the Mitchell'
  - _id:         'patterson'
    name:        'Cooley And The Gang'
  - _id:         'gates'
    name:        'It''s Miller Time'
  - _id:         'yale'
    name:        'Mr. Rodger''s Shady Hood'
  - _id:         'nyle'
    name:        'Finkle is Einhorn'
  - _id:         'lamont'
    name:        'Some guys like old balls'
  - _id:         'penn'
    name:        'I''ll show my Ditka'
  - _id:         'kyle'
    name:        'RIP Alex Rodriguez'
  - _id:         'dev'
    name:        'Turn Down for Watt'
